//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverwatchStats.WCF.Test.CleanUpService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CleanUpService.ICleanUpService")]
    public interface ICleanUpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICleanUpService/DeleteUser", ReplyAction="http://tempuri.org/ICleanUpService/DeleteUserResponse")]
        void DeleteUser(System.Guid profileGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICleanUpService/DeleteUser", ReplyAction="http://tempuri.org/ICleanUpService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(System.Guid profileGuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICleanUpServiceChannel : OverwatchStats.WCF.Test.CleanUpService.ICleanUpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CleanUpServiceClient : System.ServiceModel.ClientBase<OverwatchStats.WCF.Test.CleanUpService.ICleanUpService>, OverwatchStats.WCF.Test.CleanUpService.ICleanUpService {
        
        public CleanUpServiceClient() {
        }
        
        public CleanUpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CleanUpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CleanUpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CleanUpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteUser(System.Guid profileGuid) {
            base.Channel.DeleteUser(profileGuid);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(System.Guid profileGuid) {
            return base.Channel.DeleteUserAsync(profileGuid);
        }
    }
}
